#!/bin/bash
# install.sh - build "Usage HUD.app" and install the HUD for the current user.
#
# What it does:
#   1. Finds a Python 3 interpreter that has Tk support (tries plain `python3`
#      on PATH, uv-managed installs, Homebrew, and python.org framework
#      installs, in that order).
#   2. Copies usage_hud.py into ~/.usage-hud/ (or $USAGE_HUD_HOME), so the
#      app keeps working after you delete this cloned repo.
#   3. Builds a small .app bundle that launches it, and installs that bundle
#      into ~/Applications (or --dest).
#
# Usage:
#   ./install.sh [--dest DIR] [--python PATH] [--name NAME] [--launch]
#
#   --dest DIR      where to install the .app (default: ~/Applications)
#   --python PATH   use this interpreter instead of auto-detecting one
#   --name NAME     app bundle display name (default: Usage HUD)
#   --launch        open the app once installation finishes

set -euo pipefail

if [ "$(uname -s)" != "Darwin" ]; then
    echo "install.sh builds a macOS .app bundle; this only works on macOS." >&2
    echo "On other platforms, just run: python3 usage_hud.py" >&2
    exit 1
fi

DEST="$HOME/Applications"
APP_NAME="Usage HUD"
PYTHON_OVERRIDE=""
DO_LAUNCH=0

while [ $# -gt 0 ]; do
    case "$1" in
        --dest) DEST="$2"; shift 2 ;;
        --python) PYTHON_OVERRIDE="$2"; shift 2 ;;
        --name) APP_NAME="$2"; shift 2 ;;
        --launch) DO_LAUNCH=1; shift ;;
        -h|--help)
            sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) echo "unknown argument: $1" >&2; exit 1 ;;
    esac
done

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="${USAGE_HUD_HOME:-$HOME/.usage-hud}"

# ---------------------------------------------------------------------------
# 1. find a Python 3 with Tk support
# ---------------------------------------------------------------------------

has_tkinter() {
    "$1" -c "import tkinter" >/dev/null 2>&1
}

find_python() {
    if [ -n "$PYTHON_OVERRIDE" ]; then
        if has_tkinter "$PYTHON_OVERRIDE"; then
            echo "$PYTHON_OVERRIDE"
            return 0
        fi
        echo "! --python $PYTHON_OVERRIDE has no working tkinter" >&2
        return 1
    fi

    # plain python3 on PATH (Homebrew, python.org, pyenv, etc.)
    if command -v python3 >/dev/null 2>&1; then
        local p
        p="$(command -v python3)"
        has_tkinter "$p" && { echo "$p"; return 0; }
    fi

    # uv-managed interpreters, newest first
    local uv_py
    for uv_py in $(ls -d "$HOME"/.local/share/uv/python/cpython-3.*/bin/python3 2>/dev/null | sort -rV); do
        has_tkinter "$uv_py" && { echo "$uv_py"; return 0; }
    done

    # python.org framework installs, newest first
    local fw_py
    for fw_py in $(ls -d /Library/Frameworks/Python.framework/Versions/3.*/bin/python3 2>/dev/null | sort -rV); do
        has_tkinter "$fw_py" && { echo "$fw_py"; return 0; }
    done

    return 1
}

echo "Looking for a Python 3 with Tk support..."
if ! PYTHON_BIN="$(find_python)"; then
    cat >&2 <<'EOF'

! No Python 3 with tkinter was found.

Fix one of these ways, then re-run ./install.sh:
  - uv:        uv python install 3.12
  - Homebrew:  brew install python-tk
  - python.org: download the installer from python.org (bundles Tk)
EOF
    exit 1
fi
echo "Using: $PYTHON_BIN"

# ---------------------------------------------------------------------------
# 2. install the script into the state dir
# ---------------------------------------------------------------------------

mkdir -p "$STATE_DIR"
cp "$REPO_DIR/usage_hud.py" "$STATE_DIR/usage_hud.py"
chmod +x "$STATE_DIR/usage_hud.py"
echo "Installed script: $STATE_DIR/usage_hud.py"

# ---------------------------------------------------------------------------
# 3. build the .app bundle
# ---------------------------------------------------------------------------

mkdir -p "$DEST"
APP="$DEST/$APP_NAME.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>$APP_NAME</string>
	<key>CFBundleDisplayName</key>
	<string>$APP_NAME</string>
	<key>CFBundleIdentifier</key>
	<string>local.usage-hud</string>
	<key>CFBundleVersion</key>
	<string>1.0</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleExecutable</key>
	<string>usage-hud-launcher</string>
	<key>LSUIElement</key>
	<true/>
	<key>LSMinimumSystemVersion</key>
	<string>10.13</string>
	<key>NSHighResolutionCapable</key>
	<true/>
</dict>
</plist>
PLIST

LAUNCHER="$APP/Contents/MacOS/usage-hud-launcher"
cat > "$LAUNCHER" <<LAUNCH
#!/bin/bash
# Generated by install.sh - do not edit by hand, re-run install.sh instead.
set -u
PY="$PYTHON_BIN"
SCRIPT="$STATE_DIR/usage_hud.py"
LOG="$STATE_DIR/hud.log"

if [ ! -x "\$PY" ]; then
    osascript -e "display alert \"$APP_NAME\" message \"Python interpreter not found: \$PY. Re-run install.sh from the usage-hud repo.\" as critical"
    exit 1
fi
if [ ! -f "\$SCRIPT" ]; then
    osascript -e "display alert \"$APP_NAME\" message \"Script not found: \$SCRIPT. Re-run install.sh from the usage-hud repo.\" as critical"
    exit 1
fi

exec "\$PY" "\$SCRIPT" >> "\$LOG" 2>&1
LAUNCH
chmod +x "$LAUNCHER"

xattr -cr "$APP" 2>/dev/null || true

echo "Installed app:    $APP"
echo
echo "Done. Double-click \"$APP_NAME.app\" in $DEST to start it,"
echo "or add it to Login Items (System Settings > General > Login Items) to autostart."
echo
echo "To feed it live Claude Code quota data, run:"
echo "  \"$PYTHON_BIN\" \"$STATE_DIR/usage_hud.py\" --install-claude-statusline"

if [ "$DO_LAUNCH" -eq 1 ]; then
    open "$APP"
fi
